
all:
	$(MAKE) -C Model
	$(MAKE) -C RockSalt
	$(MAKE) -c REINS

clean: 
	rm Model/*.vo
	rm Model/*.v.d
	rm Model/*.glob
	rm RockSalt/*.vo
	rm RockSalt/*.v.d
	rm RockSalt/*.glob
	rm REINS/*.vo
	rm REINS/*.v.d
	rm REINS/*.glob
